# Configuraci칩n de Build para Netlify
[build]
  command = "npm run build" # El comando que Netlify ejecutar치 para construir tu sitio
  publish = "dist"          # La carpeta que Netlify desplegar치

# Redirecci칩n para Single Page Applications (SPA) como React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200